### ISSUE TITLE
this is my logs.

### ISSUE THREAD

**Issue by ixayldz** [dechristopher/talon#42]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle talon@1.4.0~prestart: talon@1.4.0
6 info lifecycle talon@1.4.0~start: talon@1.4.0
7 verbose lifecycle talon@1.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle talon@1.4.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle talon@1.4.0~start: CWD: /home
10 silly lifecycle talon@1.4.0~start: Args: [ '-c', 'TALON_DEV=false node server.js' ]
11 silly lifecycle talon@1.4.0~start: Returned: code: 1  signal: null
12 info lifecycle talon@1.4.0~start: Failed to exec start script
13 verbose stack Error: talon@1.4.0 start: `TALON_DEV=false node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid talon@1.4.0
15 verbose cwd /home
16 verbose Linux 3.10.0-1062.1.1.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.24.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error talon@1.4.0 start: `TALON_DEV=false node server.js`
22 error Exit status 1
23 error Failed at the talon@1.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dechristopher** [comment]
Why are you using this project? It's an ancient, deprecated codebase that needs a very specific environment and set of supporting services to run. Don't waste your time.

**Comment by ixayldz** [comment]
ohh i understand? i find all github but there is not a working one for csgo
matchmaking. do you have plan simple matchmaking platform make in future ?

Andrew DeChristopher ***@***.***>, 19 Ağu 2021 Per, 17:18
tarihinde şunu yazdı:

**Comment by dechristopher** [comment]
Frankly, no. This was a very simple backend for a C# matchmaking client that was in use about 6 years ago. You won't find any fully-made matchmaking platform on GitHub that's open source. I suggest doing some research and making your own.

**Comment by ixayldz** [comment]
okey thank you anyway.

Andrew DeChristopher ***@***.***>, 19 Ağu 2021 Per, 17:22
tarihinde şunu yazdı:
